// EN: Variable names have been checked and replaced with self-descriptive names
// CZ: Názvy proměnných byly zkontrolovány a nahrazeny samopopisnými názvy
global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Text;
global using System.Diagnostics;
global using System.Collections;
global using System.IO;
global using SunamoDateTime.Converters;
global using SunamoDateTime.Data;
global using SunamoDateTime.DT;
global using SunamoDateTime._sunamo.SunamoBts;
global using SunamoDateTime._sunamo.SunamoExtensions;
global using SunamoDateTime._sunamo.SunamoParsing;
global using SunamoDateTime._sunamo.SunamoStringSplit;
global using SunamoDateTime._public.SunamoEnums.Enums;
global using SunamoDateTime._sunamo.SunamoExceptions;
global using SunamoDateTime._sunamo.SunamoValues.Constants;
global using SunamoDateTime._sunamo.SunamoValues.Values;
global using System.Globalization;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoDateTime;
global using SunamoDateTime.ConvertersSimple;
global using SunamoDateTime._public;
global using SunamoDateTime._sunamo;
global using SunamoDateTime._sunamo.SunamoData.Data;
global using SunamoDateTime._sunamo.SunamoInterfaces.Interfaces;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
