name: Build SunamoDateTime

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDateTime
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDateTime/SunamoDateTime.csproj

    - name: Build
      run: dotnet build SunamoDateTime/SunamoDateTime.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDateTime.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDateTime.Tests/SunamoDateTime.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDateTime.Tests/SunamoDateTime.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDateTime.Tests/SunamoDateTime.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
